### ISSUE TITLE
Create notification message 30 minutes before op start

### ISSUE THREAD

**Issue by PatrickPedersen** [THE-BWC/DiscordOperationsBot#4]
30 minutes before the OP starts, the bot should post a message about the OP beginning in a specific game channel (possibly ping the game role). This should be done even though we utilize Discord Events since not everyone knows how to use those...

**Comment by Goltred** [comment]
@PatrickPedersen I'm starting to work on this one... and I was wondering if you wanted to reproduce the same behavior as the current bot.
I noticed that keeps track of which ops have been notified so that it doesn't send the message twice, but before adding this to the current  codebase I wanted to touch base to see if you had any other ideas on how to handle this.

I was thinking that maybe we could switch some things around a bit in the new infrastructure... since we know that we want to have an opserv backend, perhaps it might be a good idea to do this as a sort of push event from opserv instead.

So:
- Opserv would have an internal service that checks periodically if ops need to be notified and keeps its own track if they have been notified
- If there are ops that need to be notified, push a request to send the message to the discord bot
- The bot is just waiting for a notification request from "somewhere" and it just relays the information.

Thoughts?

**Comment by PatrickPedersen** [comment]
Yeah,  OpServ is sort of already doing it that way, when it comes to posting the Discord Events. Since OpServ contacts the bot and tells it that a new operation has been posted.

So, that should work if we set up a cron that runs a check against the DB periodically.
I can make those modifications on the OpServs side.
